### ISSUE TITLE
Node integration section references server.js without first creating it

### ISSUE THREAD

**Issue by wKovacs64** [mswjs/mswjs.io#11]
[Getting Started > Integrate > Node](https://mswjs.io/docs/getting-started/integrate/node) talks about importing `src/mocks/server.js` to stop and start the server, but the reader has not yet created that file. The Node section probably needs a step where that file is created, similar to the [Configure Worker](https://mswjs.io/docs/getting-started/integrate/browser#configure-worker) step in the browser integration section.

**Comment by kettanaito** [comment]
That's a nice catch, @wKovacs64! I've overlooked the module creation step.
