### ISSUE TITLE
Typo "propery"

### ISSUE THREAD

**Issue by andykao1213** [mswjs/mswjs.io#113]
Hi guys!
First of all, thanks for this amazing project which helps me a lot!
I found a typo in [query-parameter page](https://mswjs.io/docs/recipes/query-parameters)

> In order to access a query parameter of the intercepted request, use the searchParams propery on the req.url instance

I think it should be "property" instead of "propery".
I would like to open a PR to fix the typo.
Thank you!

**Comment by andykao1213** [comment]
Open a PR here #114

**Comment by kettanaito** [comment]
Thank you for fixing that, @andykao1213! 🎉
