### ISSUE TITLE
Remove '$' character from the command in official docs.

### ISSUE THREAD

**Issue by mrdulin** [mswjs/mswjs.io#117]
**Is your feature request related to a problem? Please describe.**

For example, a command from the section: https://mswjs.io/docs/getting-started/integrate/browser#configure-worker:

```
$ touch src/mocks/browser.js
```

There is a copy button at the end of the command, it will copy the unnecessary character `$`. That will make the command failed if you press enter without deleting `$` character.

```console
^ react-components [master] $ touch src/mocks/browser.js
zsh: command not found: $
```

**Describe the solution you'd like**

Put the `$` character where it cannot be copied. Or make it as an icon.

**Comment by kettanaito** [comment]
Hi, @hubgit. That's also a viable option. I don't mind either as the solution to this. Would you be interested in making a pull request to your [website repository](https://github.com/mswjs/mswjs.io) that removes `$` from all bash commands?

**Comment by aminamos** [comment]
I think this can be closed @kettanaito

**Comment by kettanaito** [comment]
Thanks for double-checking on this, @aminamos! 🎉
