### ISSUE TITLE
Adds "Get involved" link/page

### ISSUE THREAD

**Issue by kettanaito** [mswjs/mswjs.io#13]
For a new contributor it may be confusing how to get into the project. I suggest we add a "Get involved" link, or a page, that would describe how they can help.

There are multiple ways to help:

1. Review and edit the documentation.
1. Get started with the `help wanted` and `good first issue` issues in the MSW repo.
1. Generally describe what libraries are used, what is their relation, so people may find a field they are most interested in.

**Comment by timdeschryver** [comment]
I think this can be closed, we have https://mswjs.io/get-involved now 🙂

**Comment by kettanaito** [comment]
Thanks for bumping this, @timdeschryver. I've forgotten this was open.
