### ISSUE TITLE
Things to notice when update `msw` to a newer version

### ISSUE THREAD

**Issue by nvh95** [mswjs/mswjs.io#130]
I think the document should have something like **Things to notice when update `msw` to a newer version**. Since usually to update, people only do `npm install --save-dev msw@{version|tag}`. If they are using `msw` to work with the browser, they need to re-generate the `mockServiceWorker.js` file by executing `npx msw init <PUBLIC_DIR>` as well (in case there is any change).

In my case, I update `msw` from `0.19.x` to `0.24.x` and it didn't work. It took me a while to figure out that I should update `mockServiceWorker.js` as well. I think we should mention it in the docs to save other people's time.
@kettanaito 
Reference: The difference of `mockServiceWorker.js` between `0.19.x` and `0.24.x`
https://www.diffchecker.com/11a1JE0u

**Comment by kettanaito** [comment]
Hey, @nvh95. That sounds like a good thing to mention.

There is always an error message in the browser suggesting you should update the worker file if it's behind the latest published one. Did you happen to see that while upadting?

**Comment by nvh95** [comment]
@kettanaito I'm not sure if I saw one. I did the update a few weeks ago. I will reproduce and let you know.
But I do remember I experienced struggle even after update `mockServiceWorker.js`, I have to unregister msw by myself manually through Google Dev Tools then refresh my application to make it work. I will try to reproduce it also and let you know.

**Comment by kettanaito** [comment]
Manual unregistering shouldn't be necessary. Try Hard reloading (Cmd + Shift + R / Ctrl + Shift + R) the page instead.

**Comment by kettanaito** [comment]
Installing/updating to v28.x and running `npx msw init` command will prompt you to save the public directory into your package.json. This will ease the update path, with `npm i msw` with the next versions updating the worker script automatically. [Read more here](https://mswjs.io/docs/faq#why-do-i-see-the-detected-outdated-service-worker-error-in-my-console).
