### ISSUE TITLE
Adds the "Examples" page

### ISSUE THREAD

**Issue by kettanaito** [mswjs/mswjs.io#14]
## What

Need to add the "Examples" page to the website.

## Why

Current "Examples" link in the header points to the GitHub repository. I think it would be much  more appealing and easier to navigate through examples if we introduce some UI.

## How

1. Create `src/pages/examples.tsx`.
1. Add two sections to the Examples page: "API types" and "Libraries & Frameworks" (both can be `h2` elements).
1. Create a box component that represents a single example. Each example box should have a logo of the technology, the name of the technology, and a short description about the example.
1. Each example box is a link, which, when clicked, leads you to the respective example folder in the [Examples repository](https://github.com/mswjs/examples). For example, if I click on the "GraphQL example", it should link me to [this folder](https://github.com/mswjs/examples/tree/master/examples/graphql-react-apollo).
1. Update the "Examples" link in the `src/components/header.tsx` to point to the local page (`/examples`).

**Comment by dandelionadia** [comment]
I will do it.
