### ISSUE TITLE
Clicking on the left Navigation scrolls to top for both left navigation bar and page

### ISSUE THREAD

**Issue by anuraagbarde** [mswjs/mswjs.io#148]
If I get some guidance, I can help solve this issue, It is irritating for the left bar to also scroll to top when any menu option is clicked. I am familiar with basic reactJS.

**Comment by kettanaito** [comment]
Hey, @anuraagbarde. Thanks for reporting this. 

I'm working on a full rewrite of the documentation, and this issue is fixed there. Thus, I will close it on GitHub. If someone wants to fix it in the current version, pull requests are welcome.
