### ISSUE TITLE
Examples of Permanent override for Playwright

### ISSUE THREAD

**Issue by takefumi-yoshii** [mswjs/mswjs.io#176]
Hi, @kettanaito.
The documentation currently has only [Cypress example](https://mswjs.io/docs/api/setup-worker/use#permanent-override), but we can do the same with [Playwright](https://playwright.dev/).
Below code works fine as far as I've tried.

```typescript
const url = (path) => `http://localhost:3000${path}`;

test.beforeEach(async ({ page }, testInfo) => {
  await page.goto(url("/login"));
  await page.evaluate(() => {
    const { worker, rest } = window.msw;
    worker.use(
      rest.post(url("/login"), (req, res, ctx) => {
        return res(ctx.json({ success: true }));
      })
    );
  });
});

test("handles user authentication", async ({ page }) => {
  // Describe application interactions for this test.
});
```
Please consider whether it can be posted as a usage example.

**Comment by kettanaito** [comment]
Hey, @takefumi-yoshii. Thank you for the insights on this usage example.

I think we should create a brand new `with-playwright` example in our [Examples repo](https://github.com/mswjs/examples/tree/master/examples), and include this setup for end-to-end tests there. 

Please, would you like to give me a hand with creating this example? You can find the [contributing guidelines](https://github.com/mswjs/examples/blob/master/.github/CONTRIBUTING.md) that, hopefully, make the process smoother.

**Comment by takefumi-yoshii** [comment]
@kettanaito Offcourse ! I'll create PR this sample in the near future, thanks.

**Comment by takefumi-yoshii** [comment]
Hi, @kettanaito. I created [PR](https://github.com/mswjs/examples/pull/71) into examples. Best regards.

**Comment by kettanaito** [comment]
Thanks, @takefumi-yoshii! 🎉 I will give it a look a little later this week. That will be a superb addition to our examples collection.
