### ISSUE TITLE
setupWorker Function, order of execution ? 

### ISSUE THREAD

**Issue by SunD004** [mswjs/mswjs.io#185]
Hi 🔢 

I want to know what is the execution logic for setupWorker function 👯 
It is first router declaration to the end ( A > B > C) or (C > B > A).
Because i don't understand why my regex who catch all url of my server domain and return status 500 have the same comportement at the first position (A) and at the end position declaration (C). I have multiple mock status 200 declaration and i don't understand why when i put my regex of status 500 at the first position declaration i got the same comportment that when i declare it at the end

Thanks 👋

**Comment by kettanaito** [comment]
Hi, @SunD004.

Request handlers you provide to the `setupWorker` (and `setupServer`) function are executed in the exact over they are provided, that being left-to-right:

```js
setupWorker(first, second, third, ...)
```

The first handle that matches an intercepted request _and_ returns a mocked response will be used. Once an intercepted request has a mocked response, the handler lookup cycle ends immediately. 

> I have multiple mock status 200 declaration and i don't understand why when i put my regex of status 500 at the first position declaration i got the same comportment that when i declare it at the end

Do you mind sharing a reproduction example of this? I'd be happy to give you a hand with getting your use case to work. 

One of the common things that happen is people forget to clear cache in-between tests, which results in stale responses as if the handler does not get applied.

**Comment by SunD004** [comment]
> Hi, @SunD004.
> 
> Request handlers you provide to the `setupWorker` (and `setupServer`) function are executed in the exact over they are provided, that being left-to-right:
> 
> ```js
> setupWorker(first, second, third, ...)
> ```
> 
> The first handle that matches an intercepted request _and_ returns a mocked response will be used. Once an intercepted request has a mocked response, the handler lookup cycle ends immediately.
> 
> > I have multiple mock status 200 declaration and i don't understand why when i put my regex of status 500 at the first position declaration i got the same comportment that when i declare it at the end
> 
> Do you mind sharing a reproduction example of this? I'd be happy to give you a hand with getting your use case to work.
> 
> One of the common things that happen is people forget to clear cache in-between tests, which results in stale responses as if the handler does not get applied.

Ok thank you that makes sense I think I have badly reloaded my environment then!  Thank you
