### ISSUE TITLE
rest.all documentation

### ISSUE THREAD

**Issue by RyanClementsHax** [mswjs/mswjs.io#196]
It seems that `rest.all` that was added with [this pull request](https://github.com/mswjs/msw/pull/896) isn't mentioned in the [documentation](https://mswjs.io/docs/api/rest#methods). Is this intentional?

Thanks

**Comment by kettanaito** [comment]
Hey, @RyanClementsHax. Thanks for bringing this up.

I've added `rest.all()` under the "Custom methods" section on [this page](https://mswjs.io/docs/api/rest#custom-methods). It's documented now.
