### ISSUE TITLE
Add a full-text search feature

### ISSUE THREAD

**Issue by nvh95** [mswjs/mswjs.io#198]
# Motivation/ Personas

I am an `msw` user for a couple of years. I used to use msw like this:
```js
rest.post("*/api/project-readme", (req, res, ctx) => {
    ...
});
```
I know that `msw` recently support `baseUrl`, so I don't need to mock `*/...` anymore. So I head to https://mswjs.io/docs/ to see how I can configure that. But the documentation site currently does not have a search function. So it's very difficult for me to locate the docs and know how to do it. I might end up mocking `*/...`.

# Suggestion

- Have a search feature at https://mswjs.io/docs/. I would recommend Algolia since [it's free for open-source sites](https://www.algolia.com/for-open-source/).
- I can give you a hand if needed.

# Reference
- [Adding Search with Algolia](https://www.gatsbyjs.com/docs/adding-search-with-algolia/)

cc: @kettanaito

**Comment by kettanaito** [comment]
Hey, @nvh95. 

I agree a text search is a missing piece to our docs. I'm working on the V2 of the website right now, and it will include the Algolia search. I can only ask you to remain patient. I'd like to roll out the new website somewhen this year. I don't think I've pushed V2 to Git yet.

**Comment by nvh95** [comment]
Yeah. Thank you for your information.
