### ISSUE TITLE
global life-cycle events handlers

### ISSUE THREAD

**Issue by geritol** [mswjs/mswjs.io#217]
Hi!

Is there a way to add "global" life-cycle events that would execute for all servers?
I think it would be really helpfull for those who use msw in tests and would like to be notified ie when there is an exception withing the msw mock code.

Thanks!

**Comment by kettanaito** [comment]
Hey, @geritol. 

Since you must only have 1 `setupServer` instance in your tests, adding any life-cycle even listener to it will be global.

```js
// jest.setup.js
const server = setupServer()

// Get notified when there's a request-related exception.
server.events.on('unhandledException', (error) => {
  console.log('Oops!', error)
})

beforeAll(() => server.listen())
afterAll(() => server.close())
```
