### ISSUE TITLE
Add typescript reference to getting started docs

### ISSUE THREAD

**Issue by IanIsFluent** [mswjs/mswjs.io#220]
This page in the docs: https://mswjs.io/docs/getting-started/mocks/rest-api doesn't mention typescript - but the https://mswjs.io/ page has a TypeScript tab.

The getting started guide should provide examples in typescript as well, or a link to a getting started with TypeScript page.

**Comment by kettanaito** [comment]
Hi, @IanIsFluent. Thanks for proposing this!

We've merged a few improvements to annotating request handlers in MSW, and now have a designated [Using with TypeScript](https://mswjs.io/docs/best-practices/typescript) recipe in the docs! 

I will link to that page from the Getting started page, as well as Intercepting requests and Mocking responses pages to help developers discover the best practices of working with TypeScript.
