### ISSUE TITLE
Content "jump"

### ISSUE THREAD

**Issue by pindjur** [mswjs/mswjs.io#248]
Content jumps are occurring on many pages due to the bug in "atomic-layout" dependency. This issue affects any component that utilizes "makeResponsive" or "useResponsiveProps" directly. I'm opening an issue here to increase its visibility. For more information, please refer to [this issue](https://github.com/kettanaito/atomic-layout/issues/365).

**Comment by kettanaito** [comment]
Hey, @pindjur. Thanks for opening this. The current documentation is in a read-only mode until the works on the next version are finished sometime next month. We won't be addressing any issues at the moment. Wait a bit, and enjoy the new docs without this content jump. Thanks.
