### ISSUE TITLE
/docs/api/response results in 404

### ISSUE THREAD

**Issue by andrewmiroshnichenko** [mswjs/mswjs.io#257]
Page https://mswjs.io/docs/api/response
Was brought there by Google 
<img width="700" alt="image" src="https://github.com/mswjs/mswjs.io/assets/15054302/e1e38ceb-4951-4fbc-a204-a7a1065f64f5">

**Comment by kettanaito** [comment]
Hi. Thanks for reporting this, @andrewmiroshnichenko! I will double-check the redirects.

**Comment by kettanaito** [comment]
I've added the missing redirect. Accessing https://mswjs.io/docs/api/response will now redirect to https://mswjs.io/docs/basics/mocking-responses. This is the closest page to the previous `response` API conceptually. 

Note that 2.0 drops the `response` function altogether in favor of the Fetch API `Response` class. The redirected page will showcase how to use that class to mock responses with MSW.
