### ISSUE TITLE
Comments are hard to read in the examples due to font

### ISSUE THREAD

**Issue by CoenraadS** [mswjs/mswjs.io#260]
I was reading this page: https://mswjs.io/docs/basics/intercepting-requests

And my opinion is the font makes it a lot harder to read the comment

![image](https://github.com/mswjs/mswjs.io/assets/5593825/595656df-a768-4f35-b4ca-009cc4beb75c)

**Comment by kettanaito** [comment]
Thanks for sharing this, @CoenraadS. Do you refer to the hand-written style of the font, do I get it right? Or the color contrast?

**Comment by CoenraadS** [comment]
To the hand-written font.

**Comment by kettanaito** [comment]
@CoenraadS, does this look better? 

<img width="831" alt="Screenshot 2023-10-24 at 19 14 48" src="https://github.com/mswjs/mswjs.io/assets/14984911/6460b445-2e27-4c57-9c21-fa43c1485f71">

**Comment by CoenraadS** [comment]
Yes, much better. Thanks
