### ISSUE TITLE
Missing page at "/404/" (GraphQL operation)

### ISSUE THREAD

**Issue by okkimus** [mswjs/mswjs.io#280]
I'm setting up MSW for GraphQL server. I got following error in console:
```
Consider naming this operation or using "graphql.operation()" request handler to intercept GraphQL 
requests regardless of their operation name/type. Read more: https://mswjs.io/docs/api/graphql/operation
```

Though page https://mswjs.io/docs/api/graphql/operation doesn't exist.

**Comment by okkimus** [comment]
I suppose the correct link would be: https://mswjs.io/docs/api/graphql/#graphqloperationresolver

**Comment by kettanaito** [comment]
Hey, @okkimus. Thanks for spotting this out! 

This does look like an issue, and you are right—we should fix it right [here](https://github.com/mswjs/msw/blob/88c45ea5295fa7a47a943311dff65c99ebb3111e/src/core/handlers/GraphQLHandler.ts#L135). Would you like to give it a try in a pull request to the MSW repo? I will help you with the review and adjusting the tests too, if you want.

**Comment by okkimus** [comment]
Sure, I'll be happy to try out it in a few days! I'll be in touch if I encounter any trouble with it 🌞
