### ISSUE TITLE
Alternative Jest setup for when Request/Response/TextEncoder is not defined

### ISSUE THREAD

**Issue by azangru** [mswjs/mswjs.io#292]
There is a section in the 1->2 migration guide that addresses the problem of tests in Jest not having access to the global objects such as `Request`, `Response`, `TextEncoder`, `fetch`, etc.

The [proposed solution](https://github.com/mswjs/mswjs.io/blob/cf1a949ffb311df319efda44f4e6d030f298bbff/src/content/docs/migrations/1.x-to-2.x.mdx#L703-L748) includes installing the `undici` package, importing the missing fetch-related globals from it, and assigning them to Jest global.

I have come across a different solution for when the tests are run in jsdom environment. You may find it a bit simpler, in that it does not require any extra libraries. It assumes that you already have `jest-environment-jsdom` package installed, which you probably do if you are running your jest tests in jsdom. Here is what it involves:

1. Create a file that customizes the jsdom environment:

```js
// my-jsdom-environment.js

const JSDOMEnvironment = require('jest-environment-jsdom').default; // or import JSDOMEnvironment from 'jest-environment-jsdom' if you are using ESM modules

class MyJSDOMEnvironment extends JSDOMEnvironment {
  constructor(...args) {
    super(...args);

    // here, you have access to regular Node globals, which you can add to the test environment
    this.global.Request = Request;
    this.global.Response = Response;
    this.global.fetch = fetch;
    // ... and so on
    // you might want to add some other missing globals, unrelated to fetch, such as structuredClone
    this.global.structuredClone = structuredClone;
  }
}

module.exports = MyJSDOMEnvironment;
```

2. Update jest config to point to your new file for test environment:

```js
module.exports = {
  testEnvironment: './my-jsdom-environment',
};
```

**Comment by azangru** [comment]
@kettanaito 

I can see that the [FAQ section of the docs is already suggesting](https://github.com/mswjs/mswjs.io/blob/1fef643f107c52721b09ce7a8d8ffccedb62c49d/src/content/docs/faq.mdx#L63-L89) the use of Node globals that are injected in the `jest.config.js`. So the `1->2` migration docs could just refer to that FAQ section.

For what it's worth, I tried using Node globals in a setup file (referenced through the `setupFiles` field in Jest config); but at that point it was already too late. I'll see if injecting them in the `globals` object as described in the FAQ section works. If it does, then that would be definitely the cleanest way of doing this.

**Comment by azangru** [comment]
Just an FYI — I have tried the [approach oulined in the FAQ section](https://mswjs.io/docs/faq#referenceerror-request-is-not-defined-in-jest) (injecting Node globals into Jest in the `jest.config.js` via the `globals` field), and it did not work for me. I can only consistently inject Node globals in an environment file 🤷‍♂️ 

Jest is such an infuriating mess!

**Comment by kettanaito** [comment]
@azangru, apologies, that suggestion is incorrect. [This is the correct one](https://mswjs.io/docs/migrations/1.x-to-2.x#requestresponsetextencoder-is-not-defined-jest). I need to update the FAQ page to suggest the same solution: the `setupFiles` option in `jest.config.js`.

**Comment by BOCOVO** [comment]
> There is a section in the 1->2 migration guide that addresses the problem of tests in Jest not having access to the global objects such as `Request`, `Response`, `TextEncoder`, `fetch`, etc.
> 
> The [proposed solution](https://github.com/mswjs/mswjs.io/blob/cf1a949ffb311df319efda44f4e6d030f298bbff/src/content/docs/migrations/1.x-to-2.x.mdx#L703-L748) includes installing the `undici` package, importing the missing fetch-related globals from it, and assigning them to Jest global.
> 
> I have come across a different solution for when the tests are run in jsdom environment. You may find it a bit simpler, in that it does not require any extra libraries. It assumes that you already have `jest-environment-jsdom` package installed, which you probably do if you are running your jest tests in jsdom. Here is what it involves:
> 
> 1. Create a file that customizes the jsdom environment:
> 
> ```js
> // my-jsdom-environment.js
> 
> const JSDOMEnvironment = require('jest-environment-jsdom').default; // or import JSDOMEnvironment from 'jest-environment-jsdom' if you are using ESM modules
> 
> class MyJSDOMEnvironment extends JSDOMEnvironment {
>   constructor(...args) {
>     super(...args);
> 
>     // here, you have access to regular Node globals, which you can add to the test environment
>     this.global.Request = Request;
>     this.global.Response = Response;
>     this.global.fetch = fetch;
>     // ... and so on
>     // you might want to add some other missing globals, unrelated to fetch, such as structuredClone
>     this.global.structuredClone = structuredClone;
>   }
> }
> 
> module.exports = MyJSDOMEnvironment;
> ```
> 
> 2. Update jest config to point to your new file for test environment:
> 
> ```js
> module.exports = {
>   testEnvironment: './my-jsdom-environment',
> };
> ```

This works for me.
Thanks

**Comment by krulik** [comment]
I can confirm that this solution works, and the official suggested one *doesn't*. For me the parsing of `response.json()` hung somewhere inside undici, parsing chunk ad infinitum.
