### ISSUE TITLE
Broken link in doco

### ISSUE THREAD

**Issue by v-mwalk** [mswjs/mswjs.io#302]
Link from `https://mswjs.io/docs/api/setup-server/use` page to 'Network Behaviour Overrides' broken.

Link should be:- `https://mswjs.io/docs/best-practices/network-behavior-overrides/`

**Comment by kettanaito** [comment]
Thanks for spotting this, @v-mwalk! Please, would you like to open a pull request to fix this? You can find the "Edit on GitHub" link at the bottom of every page in the docs. Click it and edit the broken link. GitHub UI will guide you through opening a new pull request that I can review and merge for everyone to enjoy the right link!

**Comment by kettanaito** [comment]
Fixed by #333
