### ISSUE TITLE
Missing `bypass` description in listen() page.

### ISSUE THREAD

**Issue by yuki-tomioka** [mswjs/mswjs.io#303]
In the following section, bypass is described only as B.

https://mswjs.io/docs/api/setup-server/listen/#onunhandledrequest

![“screenshot” 2023-11-07 16 15 10](https://github.com/mswjs/mswjs.io/assets/25857327/8638579a-fd8a-4895-8da5-fdc6e189bddb)

**Comment by kettanaito** [comment]
Fixed. Thanks for reporting this!
