### ISSUE TITLE
Feedback: Using local HTTPS

### ISSUE THREAD

**Issue by Cedoriku** [mswjs/mswjs.io#323]
### Discussed in https://github.com/mswjs/mswjs.io/discussions/322

<div type='discussions-op-text'>

<sup>Originally posted by **Cedoriku** November 27, 2023</sup>

- [Open page](https://mswjs.io/docs/recipes/using-local-https)

## Feedback
The flags listed are not existing anymore on Chrome. Doc is outdated. Result is I can't use MSW with my local https relied development environment

</div>

**Comment by kettanaito** [comment]
Thanks for reporting this. Fixed in 4df6b84. 

Take a look at the [updated page](https://mswjs.io/docs/recipes/using-local-https) for up-to-date instructions to use local HTTPS.
