### ISSUE TITLE
Missing page at "/404/" https://mswjs.io/docs/api/setup-worker/print-handlers

### ISSUE THREAD

**Issue by dtatarenko** [mswjs/mswjs.io#332]
Expect to see a description of the **printHandlers** method of setupWorker;
Link is present at https://mswjs.io/docs/api/setup-worker

seems it should be **listHandlers** method instead?

**Comment by kettanaito** [comment]
Hi, @dtatarenko! Thanks for reporting this. Yes, you are right, the `printHandlers()` method has been removed in favor of `listHandlers()`. I will add a redirect.
