### ISSUE TITLE
Cannot retrieve XMLHttpRequest

### ISSUE THREAD

**Issue by 73k05** [mswjs/mswjs.io#355]
Hi,

Thank you for this lib ,that seems amazing!

I installed nsw on **Expo React-Native** project and I had this error:

`Cannot retrieve XMLHttpRequest response body as XML: DOMParser is not defined. You are likely using an environment that is not browser or does not polyfill browser globals correctly.`

I'm using Axios to send the request:

```
// Headers to sent alongside request to Api
const HEADERS = {
  "Access-Control-Allow-Origin": "*",
  "User-Agent": USER_AGENT,
  "Content-Type": "application/json",
};
// Create Axios Instance based on API Url & Headers config
const axiosInstance = axios.create({
  baseURL: API_URL,
  headers: HEADERS,
});
axiosInstance
    .post("/auth/login", {
      email: credentials.email,
      password: credentials.password,
    })
```
The Handler is like this
```
export const handlers = [
  http.post(`${Config.apiUrl}/auth/login`, async ({ request }) => {
    return HttpResponse.json({ name: "73k05"});
  }),
];
```

I followed the [RN tutorial](https://mswjs.io/docs/integrations/react-native) excepted the `index.js` part, I put it in `App.tsx` If anybody face this issue I'd be please to talk about it

Thank you
73k05

**Comment by 73k05** [comment]
This issue is linked to few things after having done some more researches
- ["JSON Parse error" in React Native in MSW 2](https://github.com/mswjs/msw/issues/1775#top) needs to be fixed first
  - The v2 of msw does not work with ReactNative
  - The solution proposed to [downgrade to v1](https://v1.mswjs.io/docs/getting-started/mocks/rest-api) worked for me
- The v2 of msw does need an extra line in polyfills file
  - The PR #319 should be merged
  - The documentation should be updated

I'm closing because it is duplicated in a way...

**Comment by MarcHbb** [comment]
@73k05 Did you managed to fix it ? I have the same issue

**Comment by 73k05** [comment]
Hi @MarcHbb,

sadly no, we have just used this solution 

> The solution proposed to [downgrade to v1](https://v1.mswjs.io/docs/getting-started/mocks/rest-api) worked for me

Regards
73k05
