### ISSUE TITLE
React Native integration error index.js

### ISSUE THREAD

**Issue by batu0b** [mswjs/mswjs.io#363]
```
async function enableMocking() {
  await import('./msw.polyfills');
  const {server} = await import('./src/mocks/server');
  server.listen();
}

enableMocking().then(() => {
  AppRegistry.registerComponent(appName, () => App);
});
```

this is my index.js and when i run the project  throws this error : 

**Invariant Violation: "test" has not been registered. This can happen if:
 Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
 A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes**

I have not been able to resolve this error. Could you help me

**Comment by arkk200** [comment]
I have a same issue👍

**Comment by theJovian** [comment]
How did you resolve this?

**Comment by batu0b** [comment]
@theJovian I used a different library called miragejs
