### ISSUE TITLE
Typescript graphql example on homepage is off

### ISSUE THREAD

**Issue by hsavit1** [mswjs/mswjs.io#38]
should say `graphql.mutation<Response, Variables>` instead of `graphql.mutation<Variables, Response>`

**Comment by kettanaito** [comment]
Hey, @hsavit1! Thanks for noticing that. That's indeed wrong, and it should say `Response, Variables`.

Would you like to make a pull request with this change?

**Comment by hsavit1** [comment]
opened #39
