### ISSUE TITLE
Fix dead link for Typescript

### ISSUE THREAD

**Issue by 552020** [mswjs/mswjs.io#405]
The button "Edit this page" on the page `https://mswjs.io/docs/best-practices/typescript` is pointing to a file in the repo that doesn't exist. 

<img width="1192" alt="image" src="https://github.com/mswjs/mswjs.io/assets/60273337/7b337574-8fae-4dae-9f07-c630338f37d4">
<img width="1194" alt="image" src="https://github.com/mswjs/mswjs.io/assets/60273337/bcf69e17-4dcb-4d36-9c84-a1503e6384ae">

**Comment by kettanaito** [comment]
Hi, @552020. I believe this has been fixed. That links leads to the correct file on GitHub right now.
