### ISSUE TITLE
This lib breaks storybook with wp5

### ISSUE THREAD

**Issue by AdrianDiazG** [mswjs/mswjs.io#407]
- [Open page](https://mswjs.io/docs/runbook/)

## Issue
I get infinite calls to webpack hmr

It's been impossible to implement this library with storybook and wp5, I've tried implementing a loader myself, I tried the loader from msw-storybook-addon, I also tried with a wrapper component and start-stop the worker on mount/unmount with useEffect, I tried with an empty serviceWorder, no handlers, also tried setting the scope option for the worker. It seems that no matter what, when worker.start is called I get errors and ifinite calls, this is beyond me and I can't find any related documentation anywhere

this is what I get infinitely, this also seems to hapen on storybook reload, not in the first load

<img width="656" alt="image" src="https://github.com/mswjs/mswjs.io/assets/77022615/eaf4b121-288a-488f-9c4f-ce8e750e7833">

context:

versions: 

    "msw": "^2.3.1",
    "msw-storybook-addon": "^2.0.2",
    "storybook": "^8.1.1",
    "webpack": "^5.75.0",

**Comment by kettanaito** [comment]
Hi, @AdrianDiazG. 

Can you please share the errors you get? Above is some logging that doesn't come from MSW. 

I shouldn't need any custom loaders to use MSW with Storybook. The docs in https://github.com/mswjs/msw-storybook-addon should be enough. Happy to help once you provide more details or, ideally, a reproduction repo. Thanks.

**Comment by AdrianDiazG** [comment]
thanks for the quick response @kettanaito, well, that's the thing I don't get any errors, just infinite calls when I execute worker.start or initialize in the case of the addon, however I'm not making any calls in my components, the only line I have in the worker right now is console.log('mockServiceWorker started') which I see on the first load (which doesn't produce infinite calls) but as soon as it hot reloads or if I manually reload the page, I don't see the "mockServiceWorker started" message (which is expected I think) but it makes these infinite calls, no error messages

**Comment by AdrianDiazG** [comment]
It actually seems to be [this same issue](https://github.com/mswjs/msw-storybook-addon/issues/36):

but I tried the solutions proposed unsuccessfully :(

**Comment by AdrianDiazG** [comment]
I think I finally solved it. I realized that the problem was gone if I toggled the "bypass for network" option for the service worker on developer tools, so I used the msw-storybook-addon's initialize like this:
```javascript

initialize({
  serviceWorker: {
    options: {
      updateViaCache: 'none'
    }
  }
})

```
