### ISSUE TITLE
How to integrate Direct Usage with Graph API

### ISSUE THREAD

**Issue by ethanIncentify** [mswjs/mswjs.io#57]
```
TypeError: Protocol "http:" not supported. Expected "https:"TypeError [ERR_INVALID_PROTOCOL]: Protocol "http:" not supported. Expected "https:"
```
Here is an error message I while trying to integrate my mocks with react testing library and jest. Our app is CRA. We're also using react-router-dom, and our component is tied to the route

```jsx
import React from 'react';
import { ApolloProvider } from '@apollo/client';
import { MemoryRouter as Router, Route } from 'react-router-dom';
import { render, screen } from '@testing-library/react';
import apollo from './apolloClient';
import ProjectHeader from './ProjectHeader';

it('has a test', async () => {
  const { container } = render(
    <ApolloProvider client={apollo}>
      <Router initialEntries={['/project/1']}>
        <Route path='/project/:projectId'>
          <ProjectHeader />
        </Route>
      </Router>
    </ApolloProvider>,
    {}
  );
```
I noticed that there is[ documentation about the need for an absolute path](https://mswjs.io/docs/getting-started/integrate/node#direct-usage), and example for a rest api. Is there any documentation on what should I do for a graph api?

**Comment by kettanaito** [comment]
Hey, @ethanIncentify. 

Could you please show how you set up the `setupWorker` call in your tests?

**Comment by ethanIncentify** [comment]
here is the `browser.ts` file
```ts
import { setupWorker } from 'msw';
import { handlers } from './handlers';

const worker = setupWorker(...handlers);

export { worker };
```

I can't show you the entirety of the `apollo` variable, but generally the Apollo client looks like this

```ts
const customFetch = async (uri, init) => {
  try {
    const response = await fetch(uri, init);

    // ...

    return response;
  } catch (e) {
    handleErrors(e)
  }
}

const graqhQLLink = createHttpLink({ 
  uri: `${process.env.REACT_APP_URL}graphql`, // the env variable follows https protocol
  fetch: customFetch
});

const apollo = new ApolloClient({
  link: ApolloLink.from([/* other links */, graphQLLink]),
  cache: new InMemoryCache(),
});
```

**Comment by ethanIncentify** [comment]
@kettanaito Thanks for the hint, I was making an ajax call in the customFetch to an endpoint outside of `${process.env.REACT_APP_URL}graphql`. Creating a separate ApolloProvider specific for the testing environment seems to do the trick. Closing this issue.
