### ISSUE TITLE
How to await API response resolved in Jest tests

### ISSUE THREAD

**Issue by slaweet** [mswjs/mswjs.io#61]
## The context
I'm trying to migrate my jest tests from mocking axios to msw (something like what's suggested in https://kentcdodds.com/blog/stop-mocking-fetch). Mostly it works :tada: 

## The problem
Tests sometimes don't wait for api requests to be resolved. So the tests fail randomly (race condition).

The solution that worked when I was mocking axios is https://www.npmjs.com/package/flush-promises

Could the msw docs describe how to handle this?

**Comment by kettanaito** [comment]
Hey, @slaweet.

It is not the responsibility of MSW to await responses. _You_ perform an actual request, and you get the mocked response. MSW ensures it captures a request how you described, and responds with whichever mocked data you want. It's your app's responsibility to await the response, there's nothing new in that:

```js
const res = await fetch('https://my.backend.dev')
```

In the Kent's article the part that await for response is `await screen.findByRole('alert')`. Notice that it's an async assertion, thus there is the `await` keyword, which ensures the Promise returned by `screen.findByRole` is resolved prior to running the assertion. 

Please, whenever you face an issue, include the way how you use mocks and how you perform an actual request. This information is automatically asked of you if you [file an issue in the MSW repository](https://github.com/mswjs/msw), which I would highly encourage you to do in case of issues.

**Comment by slaweet** [comment]
Hi @kettanaito,
thank you for a thorough response.

I would very much like to handle it as in Kent's article. But I'm doing it on a project that uses [vue-test-utils](https://vue-test-utils.vuejs.org/) which doesn't provide such utility, unlike [React Testing Library](https://testing-library.com/docs/react-testing-library/intro) he's using in the article. My way around that was using https://www.npmjs.com/package/flush-promises That worked fine when I was mocking axios, but that doesn't work with MSW. 


Looks like I opened an issue in a wrong place. I opened it here, because by migrating to MSW I lost the ability to ensure there are no pending API requests in a test and I still don't quite understand why. Are there any docs that I could read to understand what are all the steps that happen when a jest test calls an API mocked by MSW? 

Thank you.

**Comment by kettanaito** [comment]
`vue-test-utils` reference the [Asynchronous testing](https://vue-test-utils.vuejs.org/guides/testing-async-components.html#asynchronous-behavior-outside-of-vue) using `axios` as an example. However, it leverages mocking of `axios.get`, which I'd not consider a good practice. 

I can recommend you to either discuss this with the maintainers of `vue-test-utils` to provide a way to await for an element to appear (seems a very common scenario even outside of async testing), or implement your own assertion utility with an interval and a timeout that await for a certain thing to happen.

Take a look at how `waitFor` is implemented in React Testing Library: https://github.com/testing-library/dom-testing-library/blob/fe04b503df13be9207769b5d61d67c5532e24636/src/wait-for.js#L21

**Comment by slaweet** [comment]
@kettanaito thank you so much for the tips. I already asked in vue-test-utils discord chat, I'll see what answers will I get there.
