### ISSUE TITLE
Invalid Google Fonts URL

### ISSUE THREAD

**Issue by nilshartmann** [mswjs/mswjs.io#85]
When opening https://mswjs.io some of the requests to Google Fonts result in HTTP 400:

<img width="1183" alt="grafik" src="https://user-images.githubusercontent.com/435073/96362177-c0275080-112b-11eb-9131-2a8b394b5d8e.png">

Invoking one of these URLs directly leads to the following error page:

`https://fonts.googleapis.com/css2?family=Source%20Code%20Pro:ital@0;2&display=swap`

<img width="560" alt="grafik" src="https://user-images.githubusercontent.com/435073/96362254-522f5900-112c-11eb-899e-42aa0da5daba.png">

Not sure, but I think in Firefox (FF 81, MacOS) this leads to missing syntax highlighting:

<img width="698" alt="grafik" src="https://user-images.githubusercontent.com/435073/96362190-e0efa600-112b-11eb-879e-ebccaf24db42.png">

(After removing 'Source Code Pro' from the styles the syntax highlighting works, so I think that might be related to the invalid requests)

**Comment by kettanaito** [comment]
Hey, @nilshartmann. Thank you for reporting this!

It appears that there's a redundant character present in the Google Font URL for Code Sans Pro in this file:

https://github.com/mswjs/mswjs.io/blob/4970ffe72d66b316a56bae7b1dd2d3b2bde6fdde/src/components/custom.scss#L2

I believe it should be:

```diff
- @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:ital@0;2&display=swap');
+ @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:ital@0&display=swap');
```

Please, would you be interested in making a pull request with such fix? That'd be awesome.

**Comment by nilshartmann** [comment]
I fixed the URLs (see #86).

Unfortunately it seems that it does not fix the Firefox rendering problem, which might be a Firefox Bug on MacOS: https://bugzilla.mozilla.org/show_bug.cgi?id=1520157. A workaround could be using another font as suggested here: https://bugzilla.mozilla.org/show_bug.cgi?id=1520157#c22

I tried Windows and Firefox renders the font correctly with colors.

**Comment by nilshartmann** [comment]
Follow up: Rendering with syntax highlighting works for me on MacOs/Firefox after removing the *locally* installed version of the Source Code Pro font.

**Comment by kettanaito** [comment]
Awesome! Thank you, @nilshartmann for tackling this :)
